services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_HOST=ollama
    volumes:
      - ./data:/app/backend/data
    ports:
      - "3000:8080"  
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    restart: unless-stopped
    depends_on:
      - ollama 

  ollama:
    image: ollama/ollama:latest  
    container_name: ollama
    environment:
      - OLLAMA_MODEL_PATH=/models   
    volumes:
      - ./models:/models 
    restart: unless-stopped
